In [2]:
import numpy as np

In [3]:
# Create list baseball
baseball_heights = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball_heights)

# Print out type of np_baseball
print(np_baseball)

# Print out the heights divided by 100
print(np_baseball / 100)

[180 215 210 210 188 176 209 200]
[1.8  2.15 2.1  2.1  1.88 1.76 2.09 2.  ]


**Array Creation and Manipulation**
   Create a 2D numpy array of shape (3, 3) filled with the number 7.


In [4]:
D = np.array([
    [7,7,7],
    [7,7,7],
    [7,7,7],
])
print(D)
D.shape


[[7 7 7]
 [7 7 7]
 [7 7 7]]


(3, 3)

**Array Indexing**
   Given a numpy array `arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])`, extract all the odd numbers from the array.

 **Array Operations**
   Given two numpy arrays `arr1 = np.array([1, 2, 3])` and `arr2 = np.array([4, 5, 6])`, perform element-wise multiplication and print the result.

 **Statistical Functions**
   Given a numpy array `arr = np.array([20, 15, 37, 35, 29])`, calculate the mean, median, and standard deviation of the array.


 **Boolean Indexing**
   Given a numpy array `arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])`, find the indices where the values are even.

**Reshaping and Flattening**
   Given a 2D numpy array `arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`, reshape it to a 1D array.

 **Array Sorting**
   Given a numpy array `arr = np.array([3, 2, 0, 1])`, sort the array in ascending order.

**Array Concatenation**
   Given two numpy arrays `arr1 = np.array([1, 2, 3])` and `arr2 = np.array([4, 5, 6])`, concatenate them into a single array.

**Broadcasting**
   Given a 2D numpy array `arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])` and a 1D array `b = np.array([1, 0, 1])`, add `b` to `arr` such that each row of `arr` is incremented by `b`.

**Random Number Generation**
    Generate a numpy array of shape (3, 2) filled with random numbers between 0 and 1.